# Inspired by https://github.com/devcontainers/images/blob/main/src/universal/.devcontainer/Dockerfile
FROM ubuntu:noble

# Why are we deleting the user 'ubuntu'?
# RUN if id "ubuntu" &>/dev/null; then \
#     echo "Deleting user 'ubuntu' for noble" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for noble"; \
#     else \
#     echo "User 'ubuntu' does not exist for noble"; \
#     fi
